name: build and test
on:
  push:
    branches: [ '*' ]
    paths: ['src/**', 'pom.xml']
  pull_request:
    branches: [ '*' ]
    paths: ['src/**', 'pom.xml']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v4
      -   uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
      -   name: maven build
          run: mvn --batch-mode --errors --show-version --no-transfer-progress --strict-checksums clean test